import React from "react";
const employeesData = [
  {
    id: 1,
    firstName: "Aarav",
    email: "employee1@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 3,
      completed: 3,
      failed: 2,
    },
    tasks: [
      {
        title: "Update client records",
        description: "Revise and update contact details in the CRM.",
        date: "2025-04-15",
        category: "Data Entry",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix login bug",
        description: "Resolve login issue reported by QA team.",
        date: "2025-04-14",
        category: "Bug Fixing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Email follow-up",
        description: "Send follow-up emails to pending clients.",
        date: "2025-04-13",
        category: "Communication",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Design new UI",
        description: "Create mockups for dashboard revamp.",
        date: "2025-05-01",
        category: "Design",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Team standup",
        description: "Daily status meeting.",
        date: "2025-05-02",
        category: "Meetings",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Database migration",
        description: "Migrate records to new schema.",
        date: "2025-05-03",
        category: "Database",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Refactor code",
        description: "Improve function structure.",
        date: "2025-05-04",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update terms page",
        description: "Fix broken links and outdated info.",
        date: "2025-05-05",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
  {
    id: 2,
    firstName: "Priya",
    email: "employee2@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 3,
      completed: 3,
      failed: 1,
    },
    tasks: [
      {
        title: "Design meeting",
        description: "Attend UI/UX sync-up meeting.",
        date: "2025-04-15",
        category: "Meetings",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Test checkout flow",
        description: "Manually test the shopping cart and checkout.",
        date: "2025-04-13",
        category: "Testing",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Create landing page",
        description: "Design layout for new campaign.",
        date: "2025-05-01",
        category: "Design",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Customer feedback analysis",
        description: "Analyze survey results.",
        date: "2025-05-02",
        category: "Analytics",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Organize project files",
        description: "Clean and structure project folders.",
        date: "2025-05-03",
        category: "Organization",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Fix broken styles",
        description: "Resolve styling bugs on product pages.",
        date: "2025-05-04",
        category: "Frontend",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Update documentation",
        description: "Ensure all features are documented.",
        date: "2025-05-05",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 3,
    firstName: "Vikram",
    email: "employee3@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 3,
      completed: 4,
      failed: 2,
    },
    tasks: [
      {
        title: "Write documentation",
        description: "Prepare API documentation for developers.",
        date: "2025-04-15",
        category: "Documentation",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update pricing page",
        description: "Revamp pricing layout as per new design.",
        date: "2025-04-14",
        category: "Frontend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Bug review",
        description: "Review reported issues and assign priorities.",
        date: "2025-04-12",
        category: "Review",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Clean repo",
        description: "Remove unused files and branches from GitHub.",
        date: "2025-04-10",
        category: "Maintenance",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Develop login UI",
        description: "Code login page with validation.",
        date: "2025-05-01",
        category: "Frontend",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Set up CI/CD",
        description: "Automate deployment with GitHub Actions.",
        date: "2025-05-02",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Update readme",
        description: "Add build instructions and usage.",
        date: "2025-05-03",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Configure Webpack",
        description: "Optimize bundles for production.",
        date: "2025-05-04",
        category: "Development",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 4,
    firstName: "Sneha",
    email: "employee4@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 3,
      completed: 4,
      failed: 0,
    },
    tasks: [
      {
        title: "Client call",
        description: "Discuss new feature requirements.",
        date: "2025-04-15",
        category: "Client Interaction",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Deploy update",
        description: "Push latest code to production server.",
        date: "2025-04-13",
        category: "DevOps",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Backup DB",
        description: "Take a full backup of database.",
        date: "2025-04-11",
        category: "Database",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Write release notes",
        description: "Summarize updates for end users.",
        date: "2025-05-01",
        category: "Documentation",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Project sync",
        description: "Weekly sync with cross-functional team.",
        date: "2025-05-02",
        category: "Meetings",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Add FAQ section",
        description: "Add common questions to help page.",
        date: "2025-05-03",
        category: "Frontend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Monitor uptime",
        description: "Check server uptime reports.",
        date: "2025-05-04",
        category: "Monitoring",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update contact page",
        description: "Add new office addresses.",
        date: "2025-05-05",
        category: "Content",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
    ],
  },
  {
    id: 5,
    firstName: "Rohan",
    email: "employee5@example.com",
    password: "123",
    taskCount: {
      active: 3,
      newTask: 3,
      completed: 4,
      failed: 2,
    },
    tasks: [
      {
        title: "SEO audit",
        description: "Run SEO audit and report issues.",
        date: "2025-04-15",
        category: "SEO",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Blog post",
        description: "Write blog on performance optimization.",
        date: "2025-04-14",
        category: "Content",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
      {
        title: "Fix mobile view",
        description: "Resolve layout issues on mobile devices.",
        date: "2025-04-13",
        category: "Frontend",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Analytics check",
        description: "Verify Google Analytics setup.",
        date: "2025-04-12",
        category: "Tracking",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Keyword research",
        description: "Find top-performing keywords.",
        date: "2025-05-01",
        category: "SEO",
        active: true,
        newTask: true,
        completed: false,
        failed: false,
      },
      {
        title: "Update privacy policy",
        description: "Add GDPR compliance notes.",
        date: "2025-05-02",
        category: "Legal",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "Post on LinkedIn",
        description: "Share product launch update.",
        date: "2025-05-03",
        category: "Social Media",
        active: false,
        newTask: false,
        completed: true,
        failed: false,
      },
      {
        title: "404 error fix",
        description: "Fix broken link on pricing page.",
        date: "2025-05-04",
        category: "Bug Fixing",
        active: false,
        newTask: false,
        completed: false,
        failed: true,
      },
    ],
  },
];

const adminData = [
  {
    id: 1,
    email: "admin@me.com",
    password: "123",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employeesData));
  localStorage.setItem("admin", JSON.stringify(adminData));
};

export const GetLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));

  return { employees, admin };
};
